### ISSUE TITLE
ArgumentNullException on RemoteControl (SignalR Hub)

### ISSUE THREAD

**Issue by Nonobis** [lucent-sea/Remotely#105]
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
Failed to invoke hub method 'RemoteControl'.

System.ArgumentNullException: Value cannot be null. (Parameter 'connectionId')
at Microsoft.AspNetCore.SignalR.DefaultHubLifetimeManager`1.SendConnectionAsync(String connectionId, String methodName, Object[] args, CancellationToken cancellationToken)
at Microsoft.AspNetCore.SignalR.Internal.SingleClientProxy`1.SendCoreAsync(String method, Object[] args, CancellationToken cancellationToken)
at Microsoft.AspNetCore.SignalR.ClientProxyExtensions.SendAsync(IClientProxy clientProxy, String method, Object arg1, Object arg2, CancellationToken cancellationToken)
at Remotely.Server.Services.BrowserSocketHub.RemoteControl(String deviceID) in C:\Build\_work\1\s\Server\Services\BrowserSocketHub.cs:line 152
at lambda_method(Closure , Object , Object[] )
at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteHubMethod(ObjectMethodExecutor methodExecutor, THub hub, Object[] arguments)
at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass13_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
Failed to invoke hub method 'RemoteControl'.

**Comment by lucent-sea** [comment]
This has been fixed.
