### ISSUE TITLE
Crash on PostgreslSQL database

### ISSUE THREAD

**Issue by Nonobis** [lucent-sea/Remotely#136]
Hello,

When using PostgresSql Database, i have this error.

**Environment :**
 - I am on lastest linux-x64 version. (ubuntu 18.04)
 - Clean postgres database

**Exception :**

SqlState: 42883
MessageText: operator does not exist: text < timestamp with time zone
Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
Position: 148
File: parse_oper.c
Line: 731
Routine: op_error
Application startup exception: Npgsql.PostgresException (0x80004005): 42883: operator does not exist: text < timestamp with time zone
at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
at Npgsql.NpgsqlDataReader.NextResult()
at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
at System.Data.Common.DbCommand.ExecuteReader()
at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result)
at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
at Microsoft.EntityFrameworkCore.DbContext.RemoveRange(IEnumerable`1 entities)
at Remotely.Server.Services.DataService.CleanupOldRecords() in C:\ProgramData\BuildAgent\_work\1\s\Server\Services\DataService.cs:line 312
at Remotely.Server.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, ApplicationDbContext context, DataService dataService, ILoggerFactory loggerFactory) in C:\ProgramData\BuildAgent\_work\1\s\Server\Startup.cs:line 236
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Exception data:
Severity: ERROR

Thanks

**Comment by lucent-sea** [comment]
The update for multiple migration sets weren't working.  They should be fixed in the latest release, though I wasn't able to test it very extensively.

The Remotely database will need to be dropped first.
