### ISSUE TITLE
Remotely Client crashing

### ISSUE THREAD

**Issue by dsinfinite** [lucent-sea/Remotely#214]
Hi,

For at least the last couple of versions the agent has been randomly crashing on many machines. There isn't any more detailed information under WER for me to provide unfortunately. Please let me know if you need anything to assist troubleshooting the cause of this, or if this issue is only affecting my environment.

Application: Remotely_Agent.exe
CoreCLR Version: 5.0.120.57516
.NET Version: 5.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: The 'SendCoreAsync' method cannot be called if the connection is not active
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.ReconnectingConnectionState.WaitForActiveConnectionAsync(String methodName, CancellationToken token, String memberName, String filePath, Int32 lineNumber)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.SendCoreAsyncCore(String methodName, Object[] args, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SignalR.Client.HubConnection.SendCoreAsync(String methodName, Object[] args, CancellationToken cancellationToken)
   at Remotely.Agent.Services.AgentSocket.SendHeartbeat() in D:\a\1\s\Agent\Services\AgentSocket.cs:line 153
   at Remotely.Agent.Services.AgentSocket.HeartbeatTimer_Elapsed(Object sender, ElapsedEventArgs e) in D:\a\1\s\Agent\Services\AgentSocket.cs:line 158
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

Faulting application name: Remotely_Agent.exe, version: 2021.1.17.1109, time stamp: 0x5fbf100e
Faulting module name: KERNELBASE.dll, version: 10.0.14393.3986, time stamp: 0x5f77fd5b
Exception code: 0xe0434352
Fault offset: 0x0000000000034f38
Faulting process id: 0x1ce8
Faulting application start time: 0x01d6eed6c659c14a
Faulting application path: C:\Program Files\Remotely\Remotely_Agent.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 71a5a945-7c94-44b3-b6bf-7d2bdd26f3c1
Faulting package full name: 
Faulting package-relative application ID:

**Comment by lucent-sea** [comment]
This should now be fixed in https://github.com/lucent-sea/Remotely/releases/tag/v2021.01.22.0533
