### ISSUE TITLE
System crash after installed 15 remotely agent - Postgres DB

### ISSUE THREAD

**Issue by sinichi19** [lucent-sea/Remotely#231]
Good Day,

Fresh installed/build from the master branch source code with postgresql-13 running on ubuntu 18.04.
When only 2 to 3  agent installed there is no problem but I noticed when we deploy the agent simultaneous on 10 computers using the quite install and local path and saw in the server the list of computers then experienced the system crash we need to refresh the browser several times to load the system.

-------
Think related to this issue.
https://github.com/lucent-sea/Remotely/issues/202

----
Error:
Error	06/02/2021 10:57:31 AM +08:00	Unknown message code: 56	Npgsql

at Npgsql.Util.PGUtil.ValidateBackendMessageCode(BackendMessageCode code) at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage) at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage) at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken) at Npgsql.NpgsqlDataReader.NextResult() at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior) at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result) at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext() at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source) at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.Find(Object[] keyValues) at Remotely.Server.Services.DataService.AddOrUpdateDevice(Device device, Device& updatedDevice) in D:\remoteNEW\remotely\Server\Services\DataService.cs:line 258 at Remotely.Server.Hubs.AgentHub.DeviceCameOnline(Device device) in D:\remoteNEW\remotely\Server\Hubs\AgentHub.cs:line 159

Error	06/02/2021 10:57:36 AM +08:00	[Error] [RequestPath:/ RequestId:0HM69JK7HI8LS:00000002 - ConnectionId:0HM69JK7HI8LS - TransportConnectionId:64HTy220dfjgWcHsQ90EYg - RequestPath:/AgentHub RequestId:0HM69JK7HI8LI:00000002 - ConnectionId:0HM69JK7HI8LI - TransportConnectionId:bpShTIwvDoaIrDCZ7Z_Gqg - RequestPath:/AgentHub RequestId:0HM69JK7HI8LD:00000002 - ConnectionId:0HM69JK7HI8LD - TransportConnectionId:rsI0rNlZdxK2HpUrjS0v7Q - RequestPath:/BrowserHub RequestId:0HM69JK7HI8L1:00000002 - ConnectionId:0HM69JK7HI8L1 - TransportConnectionId:31nS6px6Bwed0NiypKT2GA - RequestPath:/BrowserHub RequestId:0HM69JK7HI8KM:00000002 - ConnectionId:0HM69JK7HI8KM - TransportConnectionId:L9d7d4T1-hRb74QVBCrtvQ - RequestPath:/AgentHub RequestId:0HM69JK7HI8GL:00000002 - ConnectionId:0HM69JK7HI8GL - Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware] | Message: An unhandled exception has occurred while executing the request. | Exception: Unknown message code: 56

at Npgsql.Util.PGUtil.ValidateBackendMessageCode(BackendMessageCode code) at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage) at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage) at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken) at Npgsql.NpgsqlDataReader.NextResult() at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior) at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(DbContext _, Boolean result) at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext() at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source) at Remotely.Server.Pages.Pages__IndexNotLoggedIn.ExecuteAsync() in D:\remoteNEW\remotely\Server\Pages\_IndexNotLoggedIn.cshtml:line 19 at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context) at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts) at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context) at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, Object model, IView view) at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output) at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count) at Remotely.Server.Pages.Pages_Index.ExecuteAsync() in D:\remoteNEW\remotely\Server\Pages\Index.cshtml:line 22 at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context) at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts) at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context) at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode) at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync() --- End of stack trace from previous location --- at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope) at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger) at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context) at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context) at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext) at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider) at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by sinichi19** [comment]
Testing on SQLite, for now no problem encounter.

**Comment by sinichi19** [comment]
dont know if this error is also related to the 1st 1.
[Error] [TransportConnectionId:wTwILKZYAn1fK9hcMqlAtA - RequestPath:/AgentHub RequestId:0HM6AEGRPU836:00000002 - ConnectionId:0HM6AEGRPU836 - TransportConnectionId:09qXkzflEBUY5xIgqsQ_-w - RequestPath:/AgentHub RequestId:0HM6AEGRPU815:00000002 - ConnectionId:0HM6AEGRPU815 - TransportConnectionId:Mw7rWQoKYRxqYTRjUHVkng - RequestPath:/AgentHub RequestId:0HM6AEGRPU7OU:00000002 - ConnectionId:0HM6AEGRPU7OU - TransportConnectionId:TCo0HBfktLp1_py-kyymlQ - RequestPath:/AgentHub RequestId:0HM6AEGRPU7MT:00000002 - ConnectionId:0HM6AEGRPU7MT -

--

at Remotely.Server.Services.DataService.FilterUsersByDevicePermission(IEnumerable`1 userIDs, String deviceID) at Remotely.Server.Hubs.AgentHub.DeviceHeartbeat(Device device) at lambda_method125(Closure , Object , Object[] ) at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.ExecuteMethod(ObjectMethodExecutor methodExecutor, Hub hub, Object[] arguments) at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.<>c__DisplayClass16_0.<<Invoke>g__ExecuteInvocation|0>d.MoveNext()

**Comment by lucent-sea** [comment]
I'll look into this soon.

The other issue you linked was related to column data types.

According to some other issues on the repo for the Postgres DB provider, this error might be related to concurrent access to a DbContext.  It's weird that I'm not seeing it in SQLite, though, and I've had 1000+ connections on it.

I'll do some stress testing against Postgres soon and see if I can repro it.

Just for completeness, is your Postgres server on Windows or Linux?  And is the Remotely app on the same server as the DB?

**Comment by sinichi19** [comment]
@lucent-sea  thank you for your reply sir..

same server/machine of remotely, localhost only, ubuntu 18.04.

**Comment by lucent-sea** [comment]
> you mentioned 1000+ connections is that concurrent users remote the computers or 1000+ list of computers on the server.

I've had 1,000+ concurrent device connections with no issues.

I just now stood up a fresh Ubuntu  18.04 with Postgres and bombarded it with messages from 200 concurrent connections.  While they were going, I tried logging out and back in, navigating around, etc.

I couldn't generate any errors.

![image](https://user-images.githubusercontent.com/20995508/107159441-e4aa7100-6944-11eb-8fc4-015057cd076f.png)

**Comment by sinichi19** [comment]
@lucent-sea  postgresql-13 sir? will try sor today if i still encounter the same error will try the version of postgre-11 and will used the last released or older version of remotely,

saw your screen shot dont have update all for outdated device.. I encounter the error using the master branch.

thank you and more power

**Comment by lucent-sea** [comment]
Yes, I was using Postgres 13.

Are you using master from my repo or your fork? Because your fork is 108 commits behind mine.

**Comment by sinichi19** [comment]
> Yes, I was using Postgres 13.
> 
> Are you using master from my repo or your fork? Because your fork is 108 commits behind mine.

from your repo sir.using git

**Comment by lucent-sea** [comment]
What version does your server say it's running?  You can check in the About link at the bottom of the page.

**Comment by sinichi19** [comment]
![Uploading IMG_20210208_071855.jpg…]()

**Comment by sinichi19** [comment]
@lucent-sea  Sir encountered again the same problem. using last release.

Postgres-13

---
**To Reproduce:**
Fresh Install Remotely
Fresh install database postgres-13
Install 15 remotely agent 
Create 20 Device Group
Assigned 15 computers to different device group.
Restart Server/Machine
--
Think there is problem/or need to wait more minutes while server reading/loading all computers list when server restart.
----
**ERROR:**

at Npgsql.Util.PGUtil.ValidateBackendMessageCode(BackendMessageCode code) at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage) at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage) at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken) at Npgsql.NpgsqlDataReader.NextResult() at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior) at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject) at

**Comment by lucent-sea** [comment]
I did all those things.  Sorry, I can't repro it.

Also, I haven't heard of this issue from anyone else, so it might be something with your environment.

https://user-images.githubusercontent.com/20995508/107179945-94570180-698c-11eb-8f96-2294540941da.mp4

**Comment by sinichi19** [comment]
> I did all those things. Sorry, I can't repro it.
> 
> Also, I haven't heard of this issue from anyone else, so it might be something with your environment.
> 
>  FJtZpax9v5.mp4

thank you sir for this. but dont know, my ubuntu also fresh install and there is no other apps or software running only remotely and the webserver.

now not experienced the problem when using the SQLite, cause if there is something on my environment think also the SQLite not working properly. 

The difference the error yesterday the system not recover from the error, now using postgres encountered but can recover from the error .

Thank you and more power

Think I need more testing but will stay on SQLite,

**Comment by sinichi19** [comment]
Good Day,

@lucent-sea Sir, Testing on v2021.01.22.0533 with postgres-11 Ubuntu 18.04 not encounter the problem.

only saw this error but the system is working properly.  any idea sir how to fix this or i can ignore this.

[Error] [TransportConnectionId:rNJSvbqIEuUyo1e_AryKFA - RequestPath:/AgentHub RequestId:0HM6C1QHMVJIN:00000002 - ConnectionId:0HM6C1QHMVJIN - TransportConnectionId:x2bOHEf908l7YApWQVZfwQ - RequestPath:/AgentHub RequestId:0HM6C1QHMVJI8:00000002 - ConnectionId:0HM6C1QHMVJI8 - TransportConnectionId:c2rugifUk4QSUHJhb0xBhw - RequestPath:/AgentHub RequestId:0HM6C1QHMVJI6:00000002 - ConnectionId:0HM6C1QHMVJI6 -

Thank You

**Comment by sinichi19** [comment]
Will close this for now. will stay on SQLite dont why still encounter this error  when fresh install all agent and the server are working properly but when you shutdown the server for 5min and power on, after you log in to ubuntu server and wait for 5 to 10min to load all services. start encounter the problem.

Thank you and More Power

**Comment by opensource008** [comment]
sir try to set locale postgres db to (collate = en_US.UTF-8 and Ctype=En_US.UTF-8)
