### ISSUE TITLE
Remote control session only lasts for 28 seconds

### ISSUE THREAD

**Issue by BYTOOX** [lucent-sea/Remotely#268]
Hi,

After an update, we’ve discovered that the remote control session only lasts for 28 seconds, we tried downgrading the server, but the bug is still here. We tested around 5-10 versions (server and client) and still the same problem. 

Our server runs on Debian 10, it’s behind an HAProxy with SSL offloading.

Here is a suspicious log that i found :
```
● remotely.service - Remotely Server
   Loaded: loaded (/etc/systemd/system/remotely.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-04-08 17:35:28 CEST; 22h ago
 Main PID: 23860 (dotnet)
    Tasks: 16 (limit: 4697)
   Memory: 103.9M
   CGroup: /system.slice/remotely.service
           └─23860 /usr/bin/dotnet /var/www/remotely/Remotely_Server.dll

Apr 08 17:49:40 belfalas remotely[23860]:       An exception was thrown while deserializing the token.
Apr 08 17:49:40 belfalas remotely[23860]:       Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
Apr 08 17:49:40 belfalas remotely[23860]:        ---> System.Security.Cryptography.CryptographicException: The key {XXXXXXXXXXXXXXXXXXXXXXXXXXXX} was not found in the key ring.
Apr 08 17:49:40 belfalas remotely[23860]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
Apr 08 17:49:40 belfalas remotely[23860]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
Apr 08 17:49:40 belfalas remotely[23860]:          at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
Apr 08 17:49:40 belfalas remotely[23860]:          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
Apr 08 17:49:40 belfalas remotely[23860]:          --- End of inner exception stack trace ---
Apr 08 17:49:40 belfalas remotely[23860]:          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
Apr 08 17:49:40 belfalas remotely[23860]:          at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
```
If you need any other logs, please ask.

We would gladly appreciate any help.

Thanks in advance for your reply

**Comment by lucent-sea** [comment]
This is almost always because Nginx is dropping the connection.  Do you have the following entry in your Nginx config for Remotely?  If so, change `RCBrowserHub` to `ViewerHub`.

```
	location /RCBrowserHub {
		proxy_pass http://localhost:5000;
		proxy_http_version 1.1;
		proxy_set_header Upgrade \$http_upgrade;
		proxy_set_header Connection \"upgrade\";
		proxy_set_header Host \$host;
		proxy_cache_bypass \$http_upgrade;
		proxy_set_header   X-Forwarded-For \$proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Proto \$scheme;
	}
```

**Comment by lucent-sea** [comment]
Closing due to no response.

**Comment by itopie** [comment]
Hi, 

Thanks very much for your answer. My colleague is currently not available, but we've just tested your solution in our environment. It seems that it works. The connection is not interrupted.

BYTOOX is going to post a more comprehensive feedback this week regarding this issue.

Best regards

**Comment by BYTOOX** [comment]
Hi,

First of all, thank you for the answer witch seems to work as a charm.

We do have another problem, when we remote control into a W10 machine, after 3-4 minutes there is some random freezes witch obligates us to reconnect to the machine. Do you also have a fix for that ? Or maybe some logs we can send you ?

For the first problem, did the update of Remotely cause the bug, or is it a random bug ? Do we need to do this to every instance we have, even if it works correctly ?

Thanks in advance for your response.

Have a wonderful day.

**Comment by Athesis** [comment]
Hi,

I have the same problem with dropping connections after some time, with the same basic exception error message. But I don't have a RCBrowserHub entry in the ngix configuration. My current ngix "remotely" config-file looks like this:

```
server {
    listen        80 default_server;
    location / {
        proxy_pass         http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_set_header   Connection keep-alive;
        proxy_set_header   Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }

    location /BrowserHub {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
    location /AgentHub {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
    location /ViewerHub {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
    location /CasterHub {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
```
