### ISSUE TITLE
Remotely_Server_Installer Unhandled Exception after successful build

### ISSUE THREAD

**Issue by Basti-Fantasti** [lucent-sea/Remotely#276]
**Describe the bug**

After successfully finishishing the build action on github the script stops with an unhandled exception

````

Directory: /var/www/remotely/

Get artifacts response status code: OK

Trigger GitHub Actions build.

Dispatch response status code: NoContent

Build action triggered successfully.  Waiting for build
completion.

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Waiting for GitHub build completion.

Get artifacts response status code: OK

Unhandled exception. System.InvalidOperationException: Nullable object must have a value.
   at Server.Installer.Services.ServerInstaller.PerformInstall(CliParams cliParams)
   at Server.Installer.Program.Main(String[] args)
   at Server.Installer.Program.<Main>(String[] args)
Aborted

````

**To Reproduce**

Tested on Ubuntu 20.04

1. execute ./Remote_Server_Installer
2. Make sure to select true when asked for new build
3. wait for the build to be done

**Remotely Version**
Server: Current release v2021.04.13.2004 

**Expected Behavior**

Fully execute the setup procedure

**Comment by lucent-sea** [comment]
Hopefully you don't get tired of, "Here, try it again."   :D  

I replaced the installers on the [releases page](https://github.com/lucent-sea/Remotely/releases/tag/v2021.04.13.2004) if you want to give it another go.

Otherwise, I'll hopefully have time later this week to test things properly myself.  :)

**Comment by Basti-Fantasti** [comment]
Thanks I tried it again and the exception is gone!
